<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "activityindicator"
 *
 * Auto generated by Extension Builder 2022-03-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'ActivityIndicator',
    'description' => 'An extension to display whether the TU-DO Makerspace is open.',
    'category' => 'plugin',
    'author' => 'Patrick Pedersen',
    'author_email' => 'ctx.xda@gmail.com',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
